name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install tailwindcss@3.4.17
        run: npm install tailwindcss@3.4.17

      - name: Build project
        run: npx tailwindcss -i ./style.css -o ./output.css

      - name: List files (for debugging)
        run: ls -la

      - name: Create temporary directory
        run: |
          mkdir -p temp
          cp -r * temp/ || true
          cp output.css temp/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp
          force_orphan: true